Presentacion/Controllers/AccountController.cs
using System.Web.Mvc;
using System.Web.Security;
using Negocio;
using Entidad;
using System;

namespace Presentacion.Controllers
{
    public class AccountController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            if (!string.IsNullOrEmpty(User.Identity.Name)) return RedirectToAction("Index", "Home", new { Area = "" });

            ViewBag.Titulo = "Login";

            return View();
        }

        [HttpPost]
        public ActionResult Login(string Email, string Contraseña)
        {
            UsuarioEntidad usuarioEntidad = new UsuarioEntidad();
            usuarioEntidad.Email = Email;
            usuarioEntidad.Contraseña = Contraseña;
        
            if (new UsuarioNegocio().Autenticacion(usuarioEntidad))
            {
                FormsAuthentication.SetAuthCookie(Email.ToUpper(), true);

                return Json(true);
            }

            return Json(false);
        }

        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Login", "Account", new { Area = "" });
        }

        [HttpGet]
        public ActionResult Forget()
        {
            ViewBag.Titulo = "Forget";

            return View();
        }

        [HttpPost]
        public ActionResult Forget(string Email, DateTime FechaNacimiento)
        {
            UsuarioEntidad usuarioEntidad = new UsuarioEntidad();
            usuarioEntidad.Email = Email;
            usuarioEntidad.FechaNacimiento = FechaNacimiento;

            if (new UsuarioNegocio().Validacion(usuarioEntidad))
            {
                return Json(true);
            }

            return Json(false);
        }

        [HttpGet]
        public ActionResult Reset(string Token)
        {
            ViewBag.Titulo = "Reset";
            ViewBag.Token = Token;
            ViewBag.MnesajeToken = new UsuarioNegocio().ValidarToken(Token);

            return View();
        }

        [HttpPost]
        public ActionResult Reset(string Contraseña, string Token)
        {
            if (new UsuarioNegocio().RestablecerContraseña(Contraseña, Token))
            {
                return Json(true);
            }

            return Json(false);
        }
    }
}

Presentacion/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidad;
using Negocio;

namespace Presentacion.Controllers
{
    public class EmpleadoController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IngresoEmpleado(int DPI, string Nombre, int Hijos, float SalarioBase)
        {
            EmpleadoEntidad empleadoEntidad = new EmpleadoEntidad();
            empleadoEntidad.DPI = DPI;
            empleadoEntidad.Nombre = Nombre;
            empleadoEntidad.Hijo = Hijos;
            empleadoEntidad.SalarioBase = SalarioBase;

            if (new EmpleadoNegocio().CrearEmpleado(empleadoEntidad))
            {
                return Json(true);
            }

            return Json(false);
        }
    }
}

Presentacion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(User.Identity.Name)) return RedirectToAction("Login", "Account", new { Area = "" });

            return View();
        }
    }
}

Presentacion/Controllers/PalindromoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentacion.Controllers
{
    public class PalindromoController : Controller
    {

        [HttpGet]
        public ActionResult Index()
        {
         
            return View();
        }

        [HttpPost]
        public ActionResult ProcesarTexto(string Text)
        {
            string str = Text.ToLower();
            var split = str.Split(' ');

            if (split.Length == 1)
                return Json("Cantidad de palíndromos: " + CountPS(str.ToCharArray(), str.Length));
            else
                return Json("Cantidad de palíndromos: " + countPalin(Text));
        }

        private int CountPS(char[] str, int n)
        {

            int[][] dp = ReturnRectangularIntArray(n, n);
            bool[][] P = ReturnRectangularBoolArray(n, n);

            for (int i = 0; i < n; i++)
            {
                P[i][i] = true;
            }

            for (int i = 0; i < n - 1; i++)
            {
                if (str[i] == str[i + 1])
                {
                    P[i][i + 1] = true;
                    dp[i][i + 1] = 1;
                }
            }

            for (int gap = 2; gap < n; gap++)
            {
                for (int i = 0; i < n - gap; i++)
                { 
                    int j = gap + i;

                    if (str[i] == str[j] && P[i + 1][j - 1])
                    {
                        P[i][j] = true;
                    }

                    if (P[i][j] == true)
                    {
                        dp[i][j] = dp[i][j - 1] +
                                   dp[i + 1][j] + 1 - dp[i + 1][j - 1];
                    }
                    else
                    {
                        dp[i][j] = dp[i][j - 1] +
                                   dp[i + 1][j] - dp[i + 1][j - 1];
                    }
                }
            }

            return dp[0][n - 1];
        }

        private int[][] ReturnRectangularIntArray(int size1, int size2)
        {
            int[][] newArray = new int[size1][];
            for (int array1 = 0;
                     array1 < size1; array1++)
            {
                newArray[array1] = new int[size2];
            }

            return newArray;
        }

        private bool[][] ReturnRectangularBoolArray(int size1, int size2)
        {
            bool[][] newArray = new bool[size1][];
            for (int array1 = 0; array1 < size1; array1++)
            {
                newArray[array1] = new bool[size2];
            }

            return newArray;
        }

        private bool checkPalin(string word)
        {
            int n = word.Length;
            word = word.ToLower();
            for (int i = 0; i < n; i++, n--)
            {
                if (word[i] != word[n - 1])
                {
                    return false;
                }
            }
            return true;
        }

        private int countPalin(string str)
        {
            str = str + " ";

            string word = "";
            int count = 0;
            for (int i = 0; i < str.Length; i++)
            {
                char ch = str[i];

                if (ch != ' ')
                {
                    word = word + ch;
                }
                else
                {
                    if (checkPalin(word))
                    {
                        count++;
                    }
                    word = "";
                }
            }

            return count;
        }
    }
}

Presentacion/Views/Empleado/Index.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
<!DOCTYPE html>

<div class="text-center">
    <h1 class="h4 text-gray-900 mb-4">Empleados</h1>
</div>
<form class="container">
    <div class="form-group">
        <input id="DPI" name="DPI" class="form-control form-control-user" type="number" placeholder="Ingresar DPI..." autofocus />
    </div>

    <div class="form-group">
        <input id="Nombre" name="Nombre" class="form-control form-control-user" type="text" placeholder="Ingresar Nombre..." />
    </div>

    <div class="form-group">
        <input id="Hijos" name="Hijos" class="form-control form-control-user" type="number" placeholder="Ingresar Cantidad de Hijos..." onKeyUp="Calcular();" />
    </div>

    <div class="form-group">
        <input id="SalarioBase" name="SalarioBase" class="form-control form-control-user" type="number" placeholder="Ingresar Salario Base..." onKeyUp="Calcular();" />
    </div>

    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Cálculo</h1>
    </div>

    <p id="IdBonoDecreto"> </p>
    <p id="IdIGGS"> </p>
    <p id="IdIRTRA"></p>
    <p id="IdBonoPaternidad"></p>
    <p id="IdSalarioTottal"></p>
    <p id="IdSalarioLiquido"></p>

    <button id="Button_Ingresar" type="button" class="btn btn-primary btn-user btn-block">
        Guardar
    </button>
    <hr>
</form>

@section Scripts {
    <script type="text/javascript">
    function Calcular() {
            var calcSalarioBase = document.getElementById("SalarioBase").value;
            var calcCantidadHijos =  document.getElementById("Hijos").value;
            var calcBonoDecreto = 250.00;
            var calcIGGS = calcSalarioBase * 4.83 / 100;
            var calcIRTRA = calcSalarioBase * 1 / 100;
            var calcBonoParternidad = 133 * calcCantidadHijos;
            var calcSalarioTotal = parseFloat(calcSalarioBase) + calcBonoParternidad + calcBonoDecreto;
            var calcSalarioLiquido = calcSalarioTotal - calcIGGS - calcIRTRA;

            document.getElementById("IdBonoDecreto").innerHTML = "Bono Decreto: " + calcBonoDecreto.toFixed(2);
            document.getElementById("IdIGGS").innerHTML = "IGGS: " + calcIGGS.toFixed(2);
            document.getElementById("IdIRTRA").innerHTML = "IRTRA: " + calcIRTRA.toFixed(2);
            document.getElementById("IdBonoPaternidad").innerHTML = "Bono de paternidad: " + calcBonoParternidad.toFixed(2);
            document.getElementById("IdSalarioTottal").innerHTML = "Bono Total: " + calcSalarioTotal.toFixed(2);
            document.getElementById("IdSalarioLiquido").innerHTML = "Bono liquido: " + calcSalarioLiquido.toFixed(2);
        }

        $(document).ready(function () {
            var Submit = function () {
                if ($('#DPI').val() === "") {
                    alert("Debe ingresar un numero de DPI");
                    $('#DPI').focus();
                    return;
                }

                if ($('#Nombre').val() === "") {
                    alert("Debe ingresar un nombre");
                    $('#Nombre').focus();
                    return;
                }

                if ($('#Hijos').val() === "") {
                    alert("Debe ingresar una cantidad de hijos");
                    $('#Hijos').focus();
                    return;
                }

                if ($('#SalarioBase').val() === "") {
                    alert("Debe ingresar un Salario Base");
                    $('#SalarioBase').focus();
                    return;
                }

                $('#Button_Ingresar').prop("disabled", true);

                $.post(
                    '@Url.Action("IngresoEmpleado", "Empleado")',
                    {
                        DPI: $('#DPI').val(),
                        Nombre: $('#Nombre').val(),
                        Hijos: $('#Hijos').val(),
                        SalarioBase: $('#SalarioBase').val()
                    },
                    function (result) {
                        if (result) {
                            $(location).attr('href', '@Url.Action("Index", "Empleado")');
                        } else {
                            alert("No se ingreso el empleado");
                            $('#Button_Ingresar').prop("disabled", false);
                        }
                    }
                );
            };

            $('#Button_Ingresar').click(function () { Submit(); });
            $(document).keypress(function (e) { if (e.which == 13) Submit(); });
        });
    </script>
}

Presentacion/Views/Home/Index.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
<!DOCTYPE html>

<div class="text-center">
    <h1 class="h4 text-gray-900 mb-4">Prueba Tecnica</h1>
</div>

Presentacion/Views/Palindromo/Index.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="text-center">
    <h1 class="h4 text-gray-900 mb-4">Palabras Palindromas</h1>
</div>
<form class="container">
    <div class="form-group">
        <input id="Text" name="Text" class="form-control form-control-user" type="text" placeholder="Ingresar Palabras..." autofocus />
    </div>

    <button id="Button_Ingresar" type="button" class="btn btn-primary btn-user btn-block">
        Buscar
    </button>
    <hr>
</form>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            var Submit = function () {
                if ($('#Text').val() === "") {
                    alert("Debe ingresar un texto");
                    $('#Text').focus();
                    return;
                }

                $('#Button_Ingresar').prop("disabled", true);

                $.post(
                    '@Url.Action("ProcesarTexto", "Palindromo")',
                    {
                        Text: $('#Text').val()
                    },
                    function (result) {
                        alert(result);
                        $('#Button_Ingresar').prop("disabled", false);
                    }
                );
            };

            $('#Button_Ingresar').click(function () { Submit(); });
            $(document).keypress(function (e) { if (e.which == 13) Submit(); });
        });
    </script>
}

Presentacion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/wwwroot/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/wwwroot/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/wwwroot/sb-admin-2/css/sb-admin-2.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Prueba Tecnica</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbarText" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Empleado")"><b>Empleado</b></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index","Palindromo")"><b>Palíndromo</b></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout", "Account")"><b><i class="fa fa-sign-out fa-fw"></i> Salir</b></a>
                </li>
            </ul>
        </div>
    </nav>

    <br />

    @RenderBody()

    <footer class="my-3 pt-3 text-muted text-center text-small">
        <p class="mb-1">&copy; 2018-@DateTime.Now.Year Prueba Tecnica</p>
    </footer>

    <script src="~/wwwroot/jquery/jquery.js"></script>
    <script src="~/wwwroot/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/wwwroot/sb-admin-2/js/sb-admin-2.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Presentacion/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>


<html lang="es-gt">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="description" content="" />
    <meta name="author" content="">

    <title>@ViewBag.Titulo - Prueba Técnica</title>

    <link rel="stylesheet" href="~/wwwroot/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/wwwroot/font-awesome/css/font-awesome.css" />
    <link rel="stylesheet" href="~/wwwroot/sb-admin-2/css/sb-admin-2.css" />
</head>

<body class="bg-gradient-primary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-4 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-8">
                                <div class="p-5">
                                    @RenderBody()
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/wwwroot/jquery/jquery.js"></script>
    <script src="~/wwwroot/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/wwwroot/sb-admin-2/js/sb-admin-2.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>